### ISSUE TITLE
Question regarding mouse events

### ISSUE THREAD

**Issue by JeffML** [jdthorpe/react-hierarchy-tree-graph2#1]
How would mouse events (say, click on node) be handled?  Looks like react-props property of data would be the way; am I correct?

**Comment by jdthorpe** [comment]
Yep. The `path_props`, `rect_props`, and `text_props` get passed on to the various paths, rects and text.  You can attach them at the root or in the data as in the example.

**Comment by JeffML** [comment]
okay, thanks.
