### ISSUE TITLE
Embed an component within a node?

### ISSUE THREAD

**Issue by JeffML** [jdthorpe/react-hierarchy-tree-graph2#2]
Is this possible?

**Comment by jdthorpe** [comment]
Not really.  Which is to say you can add them as `children` properties of the `*_props`, but this is rendered in SVG and the box sizes are calculated manually, from the text boxes, so it won't look nice without a bunch of work.

**Comment by JeffML** [comment]
Yes, I thought there might be an issue with `children`.   Thanks for the info.
